services:
  profile_db:  
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_PROFILE_USER}
      POSTGRES_PASSWORD: ${DB_PROFILE_PASSWORD}
      POSTGRES_DB: ${DB_PROFILE_NAME}
    expose:
      - "5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_PROFILE_USER} -d ${DB_PROFILE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  profile:
    build:
      context: ./backend/services/profile_service 
      dockerfile: Dockerfile
    environment:
      DB_HOST: profile_db  
      DB_PORT: 5432
      DB_USER: ${DB_PROFILE_USER}
      DB_PASSWORD: ${DB_PROFILE_PASSWORD}
      DB_NAME: ${DB_PROFILE_NAME}
    ports:
      - "8080:8080"
    depends_on:
      profile_db:
        condition: service_healthy

volumes:
  pg_data:

networks:
  default:
    name: internal
    driver: bridge